// DO NOT EDIT THIS FILE
import cs2030s.fp.Maybe;

/**
 * Represents a student's record for a module in a particular semester.
 * A record has a student ID, a module code, an optional numeric grade
 * (None if the student is still in progress or has withdrawn), an optional
 * tutor name (None if no tutor is assigned), and a semester number.
 */
public class Record {
  private final String studentId;
  private final String module;
  private final Maybe<Double> grade;
  private final Maybe<String> tutor;
  private final int semester;

  public Record(String studentId, String module,
      Maybe<Double> grade, Maybe<String> tutor, int semester) {
    this.studentId = studentId;
    this.module    = module;
    this.grade     = grade;
    this.tutor     = tutor;
    this.semester  = semester;
  }

  public String getStudentId()   { return studentId; }
  public String getModule()      { return module; }
  public Maybe<Double> getGrade() { return grade; }
  public Maybe<String> getTutor() { return tutor; }
  public int getSemester()       { return semester; }

  @Override
  public String toString() {
    return studentId + " [" + module + "]";
  }
}
