package cs2030s.fp;

// DO NOT EDIT THIS FILE

/**
 * A generic class representing a lazily evaluated value.  A {@code Lazy<T>} is
 * either already evaluated (an {@code Evaluated} wrapping a cached value) or
 * deferred (a {@code Deferred} whose {@code Producer} is only called on the
 * first invocation of {@code get()}).  The result of the producer is cached
 * after the first call; subsequent calls return the cached value without
 * re-evaluating the producer.
 *
 * @param <T> the type of the value
 */
public abstract class Lazy<T> {

  /** Evaluates and returns the value, caching it for future calls. */
  public abstract T get();

  /** Returns true if this Lazy has already been evaluated. */
  public abstract boolean isEvaluated();

  /**
   * Returns a new {@code Lazy} that lazily applies {@code transformer} to the
   * value of this {@code Lazy}.  The transformer is not called until {@code get()}
   * is invoked on the returned {@code Lazy}.
   */
  public abstract <R> Lazy<R> map(Transformer<? super T, ? extends R> transformer);

  /**
   * Returns a new {@code Lazy} that lazily applies {@code transformer} to the
   * value of this {@code Lazy}, where the transformer returns a {@code Lazy<R>}.
   * The inner {@code Lazy} returned by the transformer is itself evaluated lazily.
   * The final result is cached after the first {@code get()} call.
   */
  public abstract <R> Lazy<R> flatMap(
      Transformer<? super T, ? extends Lazy<? extends R>> transformer);

  /**
   * Returns a {@code Maybe}: {@code Maybe.some(value)} if this Lazy's value
   * satisfies the condition, {@code Maybe.none()} otherwise.
   * Evaluates this Lazy as a side effect.
   */
  public Maybe<T> filter(BooleanCondition<? super T> condition) {
    return condition.test(this.get()) ? Maybe.some(this.get()) : Maybe.none();
  }

  // ----------------------------------------------------------------
  // Private nested class: Evaluated
  // ----------------------------------------------------------------

  private static class Evaluated<T> extends Lazy<T> {
    private final T value;

    private Evaluated(T value) {
      this.value = value;
    }

    @Override
    public T get() {
      return this.value;
    }

    @Override
    public boolean isEvaluated() {
      return true;
    }

    @Override
    public <R> Lazy<R> map(Transformer<? super T, ? extends R> transformer) {
      return Lazy.of(() -> transformer.transform(this.get()));
    }

    @Override
    @SuppressWarnings("unchecked")
    public <R> Lazy<R> flatMap(
        Transformer<? super T, ? extends Lazy<? extends R>> transformer) {
      return Lazy.of(() -> ((Lazy<R>) transformer.transform(this.get())).get());
    }

    @Override
    public String toString() {
      return "Lazy[" + this.value + "]";
    }
  }

  // ----------------------------------------------------------------
  // Private nested class: Deferred
  // ----------------------------------------------------------------

  private static class Deferred<T> extends Lazy<T> {
    private Producer<T> producer;
    private T value;

    private Deferred(Producer<T> producer) {
      this.producer = producer;
    }

    @Override
    public T get() {
      if (this.producer != null) {
        this.value    = this.producer.produce();
        this.producer = null;
      }
      return this.value;
    }

    @Override
    public boolean isEvaluated() {
      return this.producer == null;
    }

    @Override
    public <R> Lazy<R> map(Transformer<? super T, ? extends R> transformer) {
      return Lazy.of(() -> transformer.transform(this.get()));
    }

    @Override
    @SuppressWarnings("unchecked")
    public <R> Lazy<R> flatMap(
        Transformer<? super T, ? extends Lazy<? extends R>> transformer) {
      return Lazy.of(() -> ((Lazy<R>) transformer.transform(this.get())).get());
    }

    @Override
    public String toString() {
      return isEvaluated() ? "Lazy[" + this.value + "]" : "Lazy[?]";
    }
  }

  // ----------------------------------------------------------------
  // Static factory methods
  // ----------------------------------------------------------------

  /** Creates an already-evaluated Lazy wrapping {@code value}. */
  public static <T> Lazy<T> of(T value) {
    return new Evaluated<>(value);
  }

  /** Creates a deferred Lazy that evaluates {@code producer} on first get(). */
  public static <T> Lazy<T> of(Producer<T> producer) {
    return new Deferred<>(producer);
  }
}
