package cs2030s.fp;

// DO NOT EDIT THIS FILE

/**
 * A generic class representing an optional value: either {@code Some(value)}
 * or {@code None}.
 *
 * @param <T> the type of the value
 */
public abstract class Maybe<T> {

  /** Returns the value if this is Some, otherwise returns {@code other}. */
  public abstract T orElse(T other);

  /**
   * If Some(v), returns Some(transformer.transform(v)).
   * If None, returns None.
   */
  public abstract <R> Maybe<R> map(
      Transformer<? super T, ? extends R> transformer);

  /**
   * If Some(v), returns transformer.transform(v) (which is itself a Maybe).
   * If None, returns None.
   */
  public abstract <R> Maybe<R> flatMap(
      Transformer<? super T, ? extends Maybe<? extends R>> transformer);

  /**
   * If Some(v) and condition.test(v) is true, returns Some(v).
   * Otherwise returns None.
   */
  public abstract Maybe<T> filter(BooleanCondition<? super T> condition);

  @SuppressWarnings("rawtypes")
  private static final Maybe NONE = new None<>();

  // ----------------------------------------------------------------
  // Private nested class: Some
  // ----------------------------------------------------------------

  private static class Some<T> extends Maybe<T> {
    private final T value;

    private Some(T value) {
      this.value = value;
    }

    @Override
    public T orElse(T other) {
      return this.value;
    }

    @Override
    public <R> Maybe<R> map(Transformer<? super T, ? extends R> transformer) {
      return Maybe.some(transformer.transform(this.value));
    }

    @Override
    public <R> Maybe<R> flatMap(
        Transformer<? super T, ? extends Maybe<? extends R>> transformer) {
      @SuppressWarnings("unchecked")
      Maybe<R> result = (Maybe<R>) transformer.transform(this.value);
      return result;
    }

    @Override
    public Maybe<T> filter(BooleanCondition<? super T> condition) {
      return condition.test(this.value) ? this : Maybe.none();
    }

    @Override
    public boolean equals(Object obj) {
      if (obj instanceof Some<?> other) {
        return this.value.equals(other.value);
      }
      return false;
    }

    @Override
    public int hashCode() {
      return this.value.hashCode();
    }

    @Override
    public String toString() {
      return "Some(" + this.value + ")";
    }
  }

  // ----------------------------------------------------------------
  // Private nested class: None
  // ----------------------------------------------------------------

  private static class None<T> extends Maybe<T> {
    private None() {}

    @Override
    public T orElse(T other) {
      return other;
    }

    @Override
    public <R> Maybe<R> map(Transformer<? super T, ? extends R> transformer) {
      return Maybe.none();
    }

    @Override
    public <R> Maybe<R> flatMap(
        Transformer<? super T, ? extends Maybe<? extends R>> transformer) {
      return Maybe.none();
    }

    @Override
    public Maybe<T> filter(BooleanCondition<? super T> condition) {
      return Maybe.none();
    }

    @Override
    public boolean equals(Object obj) {
      return obj instanceof None<?>;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    @Override
    public String toString() {
      return "None";
    }
  }

  // ----------------------------------------------------------------
  // Static factory methods
  // ----------------------------------------------------------------

  /** Creates a Some wrapping the given value. */
  public static <T> Maybe<T> some(T value) {
    return new Some<>(value);
  }

  /** Returns the None singleton. */
  @SuppressWarnings("unchecked")
  public static <T> Maybe<T> none() {
    return (Maybe<T>) NONE;
  }
}
